// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkk_nWjzumP_tgaceVgWUeqWaXd4VQAc4',
    appId: '1:397208020688:web:71afbb3030c089a16ae0d5',
    messagingSenderId: '397208020688',
    projectId: 'peminjamanbarang-70140',
    authDomain: 'peminjamanbarang-70140.firebaseapp.com',
    storageBucket: 'peminjamanbarang-70140.firebasestorage.app',
    measurementId: 'G-GXV93XPK06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAllZdMiF_YHNupmN1ZGK8wQmcXBv-Mvic',
    appId: '1:397208020688:android:980024d361120e056ae0d5',
    messagingSenderId: '397208020688',
    projectId: 'peminjamanbarang-70140',
    storageBucket: 'peminjamanbarang-70140.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC81ZG5CFkktZteghUlET8shsa75_9aKs',
    appId: '1:397208020688:ios:3809e22394b310ac6ae0d5',
    messagingSenderId: '397208020688',
    projectId: 'peminjamanbarang-70140',
    storageBucket: 'peminjamanbarang-70140.firebasestorage.app',
    iosBundleId: 'com.example.peminjamanbarang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC81ZG5CFkktZteghUlET8shsa75_9aKs',
    appId: '1:397208020688:ios:3809e22394b310ac6ae0d5',
    messagingSenderId: '397208020688',
    projectId: 'peminjamanbarang-70140',
    storageBucket: 'peminjamanbarang-70140.firebasestorage.app',
    iosBundleId: 'com.example.peminjamanbarang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkk_nWjzumP_tgaceVgWUeqWaXd4VQAc4',
    appId: '1:397208020688:web:cab054ac3c30a1956ae0d5',
    messagingSenderId: '397208020688',
    projectId: 'peminjamanbarang-70140',
    authDomain: 'peminjamanbarang-70140.firebaseapp.com',
    storageBucket: 'peminjamanbarang-70140.firebasestorage.app',
    measurementId: 'G-0Y0M6134W1',
  );
}
